### PR TITLE
Protocol for OwlGenome

### PR DESCRIPTION
**Pull request by MHunt-tools**
Protocol for OwlGenome

### CODE REVIEW

**Comment by bkille** [comment]
Just a heads up, I do get an error when `n` is not a power of 2:
```
maximum recursion depth exceeded
```

**Comment by MHunt-tools** [comment]
Just caught that too! Update is being pushed now

**Comment by MHunt-tools** [comment]
Actually – I’m not as familiar with git pull requests. I have made the changes in my fork but I can’t find a button to submit a pull request to the main page this time. 

Any guidance would be greatly appreciated. 

Max

**Comment by bkille** [comment]
The pull request is automatically updated with your fork 🙂,  you can see the commits just above your comment.

**Comment by MHunt-tools** [comment]
Awesome, thanks! (I commented via email, so did not see the commits)

**Pull request closed without merging**
